---
name: Build Matrix of Binaries

'on':
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]*"
    branches:
      - "build-bins-*"
  # pull_request:
  workflow_dispatch:

env:
  TS_FILENAME: "grpcwebproxy"
  TS_SIG_FN: "sha256-unsigned.txt"
  SHARUN: "shasum --algorithm 256"

permissions:
  contents: read

jobs:
  builds:
    name: Build grpc-web-proxy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [linux, windows, macos]
        arch: [amd64, arm64]
        include:
          - platform: linux
            arch: riscv64
      fail-fast: false # important! even if one combo fails, others continue

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Declare Global Variables 4 GHA ${{ github.event_name }}
        id: set-ga-vars
        shell: bash
        run: |
          echo "VBRANCH=${{ github.ref_name }}" >> "$GITHUB_ENV"
          VSHA_SHORT=$(git rev-parse --short HEAD)
          echo "VSHA_SHORT=${VSHA_SHORT}" >> "$GITHUB_ENV"
          echo "VSHA_SHORT=${VSHA_SHORT}" >> "$GITHUB_OUTPUT"

      - name: Build web proxy binary
        env:
          PLATFORM: ${{ matrix.platform }}
          ARCH: ${{ matrix.arch }}
          CGO_ENABLED: 0
        shell: bash
        working-directory: go
        run: |
          if [ "${PLATFORM}" == "macos" ]; then
            GOOS="macos"
          else
            GOOS="${PLATFORM}"
          fi
          if [ "${ARCH}" == "amd64" ]; then
            GOARCH="x86_64"
          else
            GOARCH="${ARCH}"
          fi
          TARGET="${GOOS}-${GOARCH}"
          echo "TARGET=${TARGET}" >> "$GITHUB_ENV"

          mkdir -p build/${TARGET}

          if [ "${GOOS}" = "windows" ]; then
            TS_FILENAME=${TS_FILENAME}.exe
            echo "TS_FILENAME=${TS_FILENAME}" >> "$GITHUB_ENV"
          fi

          go build -o build/${TARGET}/${TS_FILENAME} ./grpcwebproxy
          cp -v ./grpcwebproxy/README.md build/${TARGET}/

          BINFILE="${TS_FILENAME}-${VBRANCH}-${VSHA_SHORT}-${TS_FILENAME}"
          echo "BINFILE=${BINFILE}" >> "$GITHUB_ENV"

      - name: Archive and Checksum Binaries
        shell: bash
        working-directory: go/build/${{ env.TARGET }}/
        run: |
          echo "Archive ${{ env.BINFILE }} too ${{ env.BINFILE }}.zip"
          echo "Compute files shasum"
          ${SHARUN} * >> "${{ env.BINFILE }}.sha256"
          echo "Show the shasum"
          cat "${{ env.BINFILE }}.sha256"
          echo "Checksum verification for files is "
          ${SHARUN} --check "${{ env.BINFILE }}.sha256"
          7z a "${{ env.BINFILE }}.zip" *
          echo "Compute archive shasum"
          ${SHARUN} "${{ env.BINFILE }}.zip" >> "${{ env.BINFILE }}.zip.sha256"
          echo "Show the shasum"
          cat "${{ env.BINFILE }}.zip.sha256"
          echo "Checksum verification archive is "
          ${SHARUN} --check "${{ env.BINFILE }}.zip.sha256"

      - name: Artifact upload for Archive
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TS_FILENAME }}_archive-${{ env.TARGET }}
          path: "${{ github.workspace }}/go/build/${{ env.TARGET }}/${{ env.BINFILE }}.zip*"

  create-release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}

    runs-on: ubuntu-latest
    needs: [ builds ]

    permissions:
      contents: write

    steps:
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          path: ${{ env.TS_FILENAME }}
          pattern: "${{ env.TS_FILENAME }}*"
          merge-multiple: true

      - name: Verify checksums and Prep Uploads
        shell: bash
        working-directory: ${{ env.TS_FILENAME }}
        run: |
          # set -xo pipefail
          VBRANCH=${{ github.ref_name }}
          sudo apt-get update
          sudo apt-get --no-install-recommends --assume-yes install dos2unix
          ls -alhtR
          if [ -f "${{ env.TS_FILENAME }}-${VBRANCH}.${{ env.TS_SIG_FN }}" ] ; then
            rm -fv "${{ env.TS_FILENAME }}-${VBRANCH}.${{ env.TS_SIG_FN }}"
          fi
          # Merge all sha256 files into one
          find . -name "*.sha256" -type f -print | xargs cat >> "${{ env.TS_FILENAME }}-${VBRANCH}.${{ env.TS_SIG_FN }}"
          dos2unix --quiet "${{ env.TS_FILENAME }}-${VBRANCH}.${{ env.TS_SIG_FN }}"
          cat "${{ env.TS_FILENAME }}-${VBRANCH}.${{ env.TS_SIG_FN }}"
          sha256sum --ignore-missing --check "${{ env.TS_FILENAME }}-${VBRANCH}.${{ env.TS_SIG_FN }}"
          ls -alhtR

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.TS_FILENAME }}*/**/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          draft: true
          allowUpdates: true
          updateOnlyUnreleased: true
          replacesArtifacts: true
